[[main]]
  name = "Getting Started"
  url = "/getting-started/mining/mine-phala"
  weight = 20

[[gettingstarted]]
  name = ""
  identifier = "gettingstarted"
  url = "/getting-started/mining/"
  weight = 1000

[[gettingstarted]]
  name = "Mining"
  identifier = "mining"
  url = "/getting-started/mining/"
  weight = 1000

[[gettingstarted]]
  name = "Staking"
  identifier = "staking"
  url = "/getting-started/staking/"
  weight = 2000

[[gettingstarted]]
  name = "Phala Developer"
  identifier = "phala-developer"
  url = "/getting-started/phala-developer/"
  weight = 3000


[[main]]
  name = "Docs"
  url = "/docs/phala-network/phala-network/"
  weight = 10

[[docs]]
  name = "Phala Network"
  identifier = "phala-network"
  url = "/docs/phala-network/"
  weight = 1000

[[docs]]
  name = "Developer Guide"
  identifier = "developer"
  url = "/docs/developer/"
  weight = 11000

[[docs]]
  name = "Tokenomics"
  identifier = "tokenomics"
  url = "/docs/tokenomics/"
  weight = 3000

[[docs]]
  name = "Governance"
  identifier = "governance"
  url = "/docs/governance/"
  weight = 4000

[[docs]]
  name = "Khala User"
  identifier = "khala-user"
  url = "/docs/khala-user/"
  weight = 5000

[[docs]]
  name = "Khala Mining"
  identifier = "khala-mining"
  url = "/docs/khala-mining/"
  weight = 6000

#[[docs]]
#  name = "Para-2 Testnet"
#  identifier = "para-mining"
#  url = "/docs/para-mining/"
# weight = 7000

[[docs]]
  name = "Runtime Bridge"
  identifier = "prb"
  url = "/docs/prb/"
  weight = 8000

[[docs]]
  name = "Maintain"
  identifier = "maintain"
  url = "/docs/maintain/"
  weight = 9000

[[docs]]
  name = "pDiem"
  identifier = "pDiem"
  url = "/docs/pDiem/"
  weight = 10000

# [[docs]]
#   name = "Gatekeeper"
#   identifier = "gatekeeper"
#   url = "/docs/gatekeeper/"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/Phala-Network/phala-wiki-next"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/PhalaNetwork"
  weight = 20

[[social]]
  name = "Discord"
  pre = "<svg width=\"24\" height=\"17\" viewBox=\"0 0 24 17\" fill=\"none\" stroke=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"> <path d=\"M9 3L8.5 1C8.5 1 6.93888 1.16863 6 1.5C5.17654 1.79063 4 2.5 4 2.5C4 2.5 3 3.5 2 7.5C1 11.5 1 13 1 13C1 13 2.06671 14.4092 3 15C4.2011 15.7603 6.5 16 6.5 16C6.5 16 7.5 15.5 8 14.5\" stroke=\"currentColor\" stroke-width=\"1.7\"/> <path d=\"M16.15 9.5C16.15 10.5981 15.4679 11.15 15 11.15C14.5321 11.15 13.85 10.5981 13.85 9.5C13.85 8.40193 14.5321 7.85 15 7.85C15.4679 7.85 16.15 8.40193 16.15 9.5Z\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"1.7\"/> <path d=\"M14.5 3L15 1C15 1 16.5611 1.16863 17.5 1.5C18.3235 1.79063 19.5 2.5 19.5 2.5C19.5 2.5 20.5 3.5 21.5 7.5C22.5 11.5 22.5 13 22.5 13C22.5 13 21.4333 14.4092 20.5 15C19.2989 15.7603 17 16 17 16C17 16 16 15.5 15.5 14.5\" stroke=\"currentColor\" stroke-width=\"1.7\"/> <path d=\"M5.45962 12.0404C5.20578 11.7865 4.79422 11.7865 4.54038 12.0404C4.28654 12.2942 4.28654 12.7058 4.54038 12.9596L5.45962 12.0404ZM19.4596 12.9596C19.7135 12.7058 19.7135 12.2942 19.4596 12.0404C19.2058 11.7865 18.7942 11.7865 18.5404 12.0404L19.4596 12.9596ZM5 12.5C4.54038 12.9596 4.54067 12.9599 4.54097 12.9602C4.54107 12.9603 4.54138 12.9606 4.5416 12.9608C4.54203 12.9613 4.5425 12.9617 4.543 12.9622C4.544 12.9632 4.54513 12.9643 4.54639 12.9656C4.5489 12.968 4.55191 12.971 4.55544 12.9743C4.5625 12.9811 4.57161 12.9898 4.5828 13.0001C4.60518 13.0207 4.63588 13.0482 4.67517 13.0816C4.75374 13.1482 4.86661 13.2382 5.01578 13.3435C5.31426 13.5542 5.75746 13.8257 6.36101 14.094C7.57042 14.6315 9.41049 15.15 12 15.15V13.85C9.58951 13.85 7.92958 13.3685 6.88899 12.906C6.36754 12.6743 5.99824 12.4458 5.76547 12.2815C5.64902 12.1993 5.56658 12.133 5.51624 12.0903C5.49107 12.069 5.47392 12.0535 5.46456 12.0448C5.45988 12.0405 5.45715 12.0379 5.45634 12.0371C5.45593 12.0367 5.456 12.0368 5.45655 12.0373C5.45683 12.0376 5.45722 12.038 5.45773 12.0385C5.45799 12.0388 5.45827 12.039 5.45859 12.0393C5.45874 12.0395 5.459 12.0398 5.45908 12.0398C5.45935 12.0401 5.45962 12.0404 5 12.5ZM12 15.15C14.5895 15.15 16.4296 14.6315 17.639 14.094C18.2425 13.8257 18.6857 13.5542 18.9842 13.3435C19.1334 13.2382 19.2463 13.1482 19.3248 13.0816C19.3641 13.0482 19.3948 13.0207 19.4172 13.0001C19.4284 12.9898 19.4375 12.9811 19.4446 12.9743C19.4481 12.971 19.4511 12.968 19.4536 12.9656C19.4549 12.9643 19.456 12.9632 19.457 12.9622C19.4575 12.9617 19.458 12.9613 19.4584 12.9608C19.4586 12.9606 19.4589 12.9603 19.459 12.9602C19.4593 12.9599 19.4596 12.9596 19 12.5C18.5404 12.0404 18.5407 12.0401 18.5409 12.0398C18.541 12.0398 18.5413 12.0395 18.5414 12.0393C18.5417 12.039 18.542 12.0388 18.5423 12.0385C18.5428 12.038 18.5432 12.0376 18.5434 12.0373C18.544 12.0368 18.5441 12.0367 18.5437 12.0371C18.5428 12.0379 18.5401 12.0405 18.5354 12.0448C18.5261 12.0535 18.5089 12.069 18.4838 12.0903C18.4334 12.133 18.351 12.1993 18.2345 12.2815C18.0018 12.4458 17.6325 12.6743 17.111 12.906C16.0704 13.3685 14.4105 13.85 12 13.85V15.15Z\" fill=\"currentColor\"/> <path d=\"M4.88336 4.29445C4.76983 4.63502 4.95389 5.00312 5.29445 5.11664C5.63502 5.23017 6.00312 5.04611 6.11664 4.70555L4.88336 4.29445ZM17.35 4.5C17.35 4.85899 17.641 5.15 18 5.15C18.359 5.15 18.65 4.85899 18.65 4.5H17.35ZM14.5 3.10836L14.4363 3.75523L14.4363 3.75523L14.5 3.10836ZM5.5 4.5C6.11664 4.70555 6.11628 4.70663 6.11592 4.7077C6.1158 4.70805 6.11544 4.70912 6.1152 4.70982C6.11473 4.71122 6.11425 4.7126 6.11378 4.71395C6.11283 4.71666 6.11189 4.71929 6.11097 4.72182C6.10912 4.7269 6.10731 4.73161 6.10557 4.73598C6.1021 4.74472 6.09889 4.75205 6.0961 4.75803C6.0905 4.77003 6.08668 4.77638 6.08588 4.77768C6.08408 4.78057 6.09554 4.7612 6.13149 4.72524C6.20337 4.65337 6.37994 4.50863 6.75605 4.34744C7.51703 4.02131 9.04295 3.65 12 3.65V2.35C8.95705 2.35 7.23297 2.72869 6.24395 3.15256C5.74506 3.36637 5.42163 3.59663 5.21226 3.80601C5.10759 3.91067 5.0331 4.00849 4.98053 4.09342C4.95434 4.13573 4.93392 4.1743 4.91806 4.20828C4.91014 4.22524 4.9034 4.24099 4.89766 4.25541C4.89479 4.26262 4.89218 4.26949 4.8898 4.276C4.88861 4.27926 4.88748 4.28243 4.88641 4.2855C4.88587 4.28704 4.88535 4.28855 4.88484 4.29005C4.88459 4.29079 4.88421 4.29189 4.88409 4.29227C4.88372 4.29336 4.88336 4.29445 5.5 4.5ZM12 3.65C12.9693 3.65 13.7722 3.68987 14.4363 3.75523L14.5637 2.46148C13.8501 2.39126 13.0041 2.35 12 2.35V3.65ZM14.4363 3.75523C16.1395 3.92283 16.8858 4.25403 17.1909 4.46664C17.2644 4.51786 17.3092 4.56008 17.3353 4.58865C17.3612 4.61698 17.3699 4.63332 17.3705 4.63452C17.3712 4.63569 17.3656 4.62539 17.3602 4.60198C17.3575 4.59052 17.3549 4.57638 17.3531 4.55935C17.3521 4.55086 17.3514 4.54168 17.3508 4.53179C17.3506 4.52685 17.3504 4.52173 17.3502 4.51643C17.3501 4.51378 17.3501 4.51109 17.3501 4.50835C17.35 4.50698 17.35 4.5056 17.35 4.50421C17.35 4.50351 17.35 4.50246 17.35 4.50211C17.35 4.50106 17.35 4.5 18 4.5C18.65 4.5 18.65 4.49893 18.65 4.49786C18.65 4.4975 18.65 4.49642 18.65 4.4957C18.65 4.49424 18.65 4.49276 18.6499 4.49127C18.6499 4.48828 18.6498 4.4852 18.6498 4.48205C18.6496 4.47574 18.6493 4.46912 18.649 4.46218C18.6482 4.44831 18.647 4.43321 18.6452 4.41696C18.6416 4.38442 18.6357 4.34744 18.6262 4.30668C18.607 4.22465 18.5742 4.12985 18.5201 4.02746C18.4106 3.82022 18.2261 3.60349 17.9341 3.40004C17.3642 3.00294 16.3605 2.63831 14.5637 2.46148L14.4363 3.75523Z\" fill=\"currentColor\"/> <path d=\"M10.15 9.5C10.15 10.5981 9.46793 11.15 9 11.15C8.53207 11.15 7.85 10.5981 7.85 9.5C7.85 8.40193 8.53207 7.85 9 7.85C9.46793 7.85 10.15 8.40193 10.15 9.5Z\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"1.7\"/> </svg>"
  url = "https://discord.com/invite/myBmQu5"
  weight = 20

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10

# New Simple Articles (wiki)

